name: 'Setup gRPC'
description: 'Setup gRPC C++ environment'
author: Stefan Verhoeven
inputs:
  grpc-version:
    description: Version of grpc to setup
    required: false
    default: 1.48.2
  token:
    description: Used to pull grpc distributions from eWaterCycle/grpc-versions. Since there's a default, this is typically not supplied by the user.
    required: false
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: box
  color: blue
