name: Validate 'setup-grpc'

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: 0 0 11 * *

jobs:
  setup-versions-from-manifest:
    name: Setup ${{ matrix.grpc }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        grpc: [1.47.3, 1.48.2, 1.51.1]
        include:
          # Not available for ubuntu-22.04
          - os: ubuntu-20.04
            grpc: 1.27.2
          - os: ubuntu-20.04
            grpc: 1.30.2
    steps:
      - uses: actions/checkout@v3
      - name: Setup gRPC
        uses: ./
        with:
          grpc-version: ${{ matrix.grpc }}
      - name: Verify gRPC
        run: |
          svn export https://github.com/grpc/grpc/tags/v${{ matrix.grpc }}/examples
          cd examples/cpp/helloworld
          mkdir build
          cd build
          cmake ..
          make -j 2 VERBOSE=1
        shell: bash
  # TODO add job for testing local build
